build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "src/*"
#  dependency_paths:
#    - "vendor"
#  excluded_paths:
#    - "vendor/*"

inherit: true

#tools:
#  external_code_coverage:
#    timeout: 300
